### ISSUE TITLE
where is sql dump mentioned in notebook 

### ISSUE THREAD

**Issue by Avyukth** [ray-project/llm-applications#53]
In Notebook, you are running 
`export SQL_DUMP_FP="/efs/shared_storage/goku/sql_dumps/gte-base_300_50.sql"`
not able to locate the file, Please help

**Comment by Chuukwudi** [comment]
`"/efs/shared_storage/goku/"` is his local directory where he saved the web pages. Further into the directory `".../sql_dumps/gte-base_300_50.sql"`, he saved the postgre variable into the directory. 

The full code (in bash) where this happened reads

```
%%bash
# Save index
export SQL_DUMP_FP="/efs/shared_storage/goku/sql_dumps/gte-base_300_50.sql"
mkdir -p $(dirname "$SQL_DUMP_FP") && touch $SQL_DUMP_FP
sudo -u postgres pg_dump -c > $SQL_DUMP_FP  # save
```

**Comment by Avyukth** [comment]
got it thanks
